import {body,fail,json,requirePermission,id,audit} from './_core.js';
import {ensureSchema} from './schema.js';
export async function onRequestGet({request,env}){const a=await requirePermission(request,env,'organization.view');if(a.error)return a.error;await ensureSchema(env);const [units,positions,slots,assignments,employees]=await Promise.all([
 env.DB.prepare('SELECT u.*,m.name manager_name FROM org_units u LEFT JOIN employees m ON m.id=u.manager_employee_id WHERE u.company_id=? ORDER BY u.sort_order,u.name_ar').bind(a.user.company_id).all(),
 env.DB.prepare('SELECT p.*,u.name_ar unit_name,(SELECT COUNT(*) FROM org_position_slots s WHERE s.position_id=p.id AND s.status="filled") filled_count FROM org_positions p JOIN org_units u ON u.id=p.unit_id WHERE p.company_id=? ORDER BY u.sort_order,p.title_ar').bind(a.user.company_id).all(),
 env.DB.prepare('SELECT s.*,p.title_ar position_title,p.unit_id FROM org_position_slots s JOIN org_positions p ON p.id=s.position_id JOIN org_units u ON u.id=p.unit_id WHERE u.company_id=? ORDER BY p.title_ar,s.slot_code').bind(a.user.company_id).all(),
 env.DB.prepare('SELECT a.*,e.name employee_name,p.title_ar position_title,u.name_ar unit_name,s.slot_code FROM employee_org_assignments a JOIN employees e ON e.id=a.employee_id JOIN org_positions p ON p.id=a.position_id JOIN org_units u ON u.id=a.unit_id JOIN org_position_slots s ON s.id=a.slot_id WHERE a.company_id=? AND a.active=1').bind(a.user.company_id).all(),
 env.DB.prepare('SELECT id,name,job,dept,status FROM employees WHERE company_id=? ORDER BY name').bind(a.user.company_id).all()
]);return json({ok:true,units:units.results||[],positions:positions.results||[],slots:slots.results||[],assignments:assignments.results||[],employees:employees.results||[]})}
export async function onRequestPost({request,env}){const a=await requirePermission(request,env,'organization.manage');if(a.error)return a.error;await ensureSchema(env);const b=await body(request);const action=b.action;
 if(action==='create_unit'){if(!b.name_ar)return fail('اسم الوحدة مطلوب.');const uid=id('unit');await env.DB.prepare('INSERT INTO org_units(id,company_id,parent_id,name_ar,name_en,code,unit_type,manager_employee_id,sort_order) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid,a.user.company_id,b.parent_id||null,b.name_ar,b.name_en||null,b.code||null,b.unit_type||'department',b.manager_employee_id||null,Number(b.sort_order||0)).run();await audit(env,a.user,'create','org_unit',uid,{name:b.name_ar});return json({ok:true,id:uid},201)}
 if(action==='create_position'){if(!b.unit_id||!b.title_ar)return fail('الوحدة والمسمى الوظيفي مطلوبان.');const pid=id('pos');const head=Math.max(1,Number(b.approved_headcount||1));await env.DB.prepare('INSERT INTO org_positions(id,company_id,unit_id,title_ar,title_en,code,level_name,approved_headcount) VALUES(?,?,?,?,?,?,?,?)').bind(pid,a.user.company_id,b.unit_id,b.title_ar,b.title_en||null,b.code||null,b.level_name||null,head).run();for(let i=1;i<=head;i++){const sid=id('slot');await env.DB.prepare('INSERT INTO org_position_slots(id,position_id,slot_code,status) VALUES(?,?,?,?)').bind(sid,pid,`${b.code||pid}-${String(i).padStart(2,'0')}`,'vacant').run()}await audit(env,a.user,'create','org_position',pid,{title:b.title_ar,headcount:head});return json({ok:true,id:pid},201)}
 if(action==='add_slot'){if(!b.position_id)return fail('المسمى الوظيفي مطلوب.');const sid=id('slot');await env.DB.prepare('INSERT INTO org_position_slots(id,position_id,slot_code,status) VALUES(?,?,?,?)').bind(sid,b.position_id,b.slot_code||sid,'vacant').run();return json({ok:true,id:sid},201)}
 if(action==='assign'){if(!b.employee_id||!b.slot_id)return fail('الموظف والشاغر مطلوبان.');const slot=await env.DB.prepare('SELECT s.*,p.id position_id,p.unit_id,p.company_id FROM org_position_slots s JOIN org_positions p ON p.id=s.position_id WHERE s.id=?').bind(b.slot_id).first();if(!slot||String(slot.company_id)!==String(a.user.company_id))return fail('الشاغر غير موجود.',404);const old=await env.DB.prepare('SELECT * FROM employee_org_assignments WHERE employee_id=? AND active=1').bind(b.employee_id).first();if(old){await env.DB.prepare('UPDATE employee_org_assignments SET active=0,effective_to=CURRENT_DATE WHERE id=?').bind(old.id).run();await env.DB.prepare('UPDATE org_position_slots SET status="vacant",employee_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(old.slot_id).run()}const aid=id('assign');await env.DB.prepare('INSERT INTO employee_org_assignments(id,company_id,employee_id,unit_id,position_id,slot_id,effective_from) VALUES(?,?,?,?,?,?,?)').bind(aid,a.user.company_id,b.employee_id,slot.unit_id,slot.position_id,b.slot_id,b.effective_from||new Date().toISOString().slice(0,10)).run();await env.DB.prepare('UPDATE org_position_slots SET status="filled",employee_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.employee_id,b.slot_id).run();await audit(env,a.user,'assign','employee_org',aid,{employee_id:b.employee_id,slot_id:b.slot_id});return json({ok:true,id:aid})}
 if(action==='unassign'){const as=await env.DB.prepare('SELECT * FROM employee_org_assignments WHERE id=? AND company_id=? AND active=1').bind(b.assignment_id,a.user.company_id).first();if(!as)return fail('التسكين غير موجود.',404);await env.DB.prepare('UPDATE employee_org_assignments SET active=0,effective_to=CURRENT_DATE WHERE id=?').bind(as.id).run();await env.DB.prepare('UPDATE org_position_slots SET status="vacant",employee_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(as.slot_id).run();return json({ok:true})}
 if(action==='delete_slot'){const slot=await env.DB.prepare('SELECT s.* FROM org_position_slots s JOIN org_positions p ON p.id=s.position_id WHERE s.id=? AND p.company_id=?').bind(b.id,a.user.company_id).first();if(!slot)return fail('الشاغر غير موجود.',404);if(slot.status==='filled')return fail('لا يمكن حذف شاغر مشغول. فك التسكين أولاً.');await env.DB.prepare('DELETE FROM org_position_slots WHERE id=?').bind(b.id).run();return json({ok:true})}
 if(action==='delete_position'){const p=await env.DB.prepare('SELECT * FROM org_positions WHERE id=? AND company_id=?').bind(b.id,a.user.company_id).first();if(!p)return fail('المسمى غير موجود.',404);const c=await env.DB.prepare('SELECT COUNT(*) c FROM employee_org_assignments WHERE position_id=? AND active=1').bind(b.id).first();if(Number(c?.c||0)>0)return fail('لا يمكن حذف مسمى عليه موظفون. فك التسكين أولاً.');await env.DB.prepare('DELETE FROM org_position_slots WHERE position_id=?').bind(b.id).run();await env.DB.prepare('DELETE FROM org_positions WHERE id=?').bind(b.id).run();return json({ok:true})}
 if(action==='delete_unit'){const c=await env.DB.prepare('SELECT COUNT(*) c FROM org_positions WHERE unit_id=?').bind(b.id).first();if(Number(c?.c||0)>0)return fail('لا يمكن حذف وحدة تحتوي على وظائف.');await env.DB.prepare('DELETE FROM org_units WHERE id=? AND company_id=?').bind(b.id,a.user.company_id).run();return json({ok:true})}
 return fail('إجراء غير معروف.');}
