import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,FileText,CalendarDays,WalletCards,UserMinus,Files,BarChart3,Settings,Search,Bell,Plus,ArrowLeft,ChevronDown,CheckCircle2,Clock3,AlertTriangle,X,Menu,Building2,GitBranch,BriefcaseBusiness,ShieldCheck,Download,Filter,Eye,Send,RefreshCw} from 'lucide-react';
import {companies,depts,branches,jobs,employeesFor,seedTransactions,leaves,notifications,roles} from './data/mock';
import {money,daysBetween,statusClass} from './utils/helpers';
import './styles/main.css';

const nav=[
 {section:'الرئيسية',items:[['dashboard','الرئيسية',LayoutDashboard]]},
 {section:'الموظفون',items:[['employees','جميع الموظفين',Users],['employee-new','إضافة موظف',Plus],['org','الهيكل التنظيمي',GitBranch],['jobs','الوظائف',BriefcaseBusiness]]},
 {section:'المعاملات',items:[['transactions','جميع المعاملات',FileText],['my-transactions','معاملاتي',FileText],['pending','المعاملات المعلقة',Clock3],['completed','المعاملات المكتملة',CheckCircle2],['rejected','المعاملات المرفوضة',X]]},
 {section:'الإجازات',items:[['leaves','طلبات الإجازات',CalendarDays],['balances','أرصدة الإجازات',CalendarDays],['leave-calendar','تقويم الإجازات',CalendarDays]]},
 {section:'الرواتب',items:[['payroll','مسيرات الرواتب',WalletCards],['payslip','مفردات الرواتب',WalletCards],['allowances','البدلات',WalletCards],['deductions','الخصومات والسلف',WalletCards]]},
 {section:'نهاية الخدمة',items:[['eos','حاسبة نهاية الخدمة',UserMinus],['terminations','سجل المنتهية خدماتهم',UserMinus]]},
 {section:'المستندات',items:[['documents','مستندات الموظفين',Files],['expiring','المستندات التي ستنتهي',AlertTriangle]]},
 {section:'التقارير',items:[['reports','التقارير',BarChart3]]},
 {section:'الإعدادات',items:[['settings','الإعدادات',Settings]]}
];

function App(){
 const [companyId,setCompanyId]=useState('elite'); const [roleId,setRoleId]=useState('hrm'); const [page,setPage]=useState(location.hash.replace('#/','')||'dashboard'); const [employees,setEmployees]=useState(employeesFor('elite')); const [transactions,setTransactions]=useState(seedTransactions); const [leaveData,setLeaveData]=useState(leaves); const [toast,setToast]=useState(''); const [modal,setModal]=useState(null); const [mobile,setMobile]=useState(false);
 const company=companies.find(c=>c.id===companyId); const role=roles.find(r=>r.id===roleId);
 const changeCompany=id=>{setCompanyId(id);setEmployees(employeesFor(id));setPage('dashboard');location.hash='/dashboard'};
 const go=p=>{setPage(p);location.hash='/'+p;setMobile(false)};
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2800)};
 const addEmployee=e=>{const emp={...e,id:`EMP-${companyId.slice(0,2).toUpperCase()}-${String(employees.length+1001).padStart(5,'0')}`,salary:+e.salary||8000,status:'على رأس العمل',joinDate:e.joinDate||'17/09/2026',phone:'05X XXX XXXX',email:'demo.employee@example.test'};setEmployees(x=>[emp,...x]);notify('تمت إضافة الموظف وتحديث إجمالي القوى العاملة');setModal(null)};
 const createLeave=l=>{const trx={id:`TRX-${Date.now().toString().slice(-8)}`,type:'طلب إجازة',employee:l.employee,requester:l.employee,date:'17/09/2026',status:'بانتظار الاعتماد',current:'مدير الإدارة',priority:'عادية',due:'19/09/2026',last:'تم إرسال الطلب',company:companyId,leaveDays:l.days};setLeaveData(x=>[{...l,id:`LV-${Date.now()}`,status:'بانتظار الاعتماد',company:companyId},...x]);setTransactions(x=>[trx,...x]);notify('تم إرسال طلب الإجازة وإنشاء معاملة مرتبطة');setModal(null)};
 const act=(id,next)=>{setTransactions(ts=>ts.map(t=>t.id===id?{...t,status:next,current:next==='مكتملة'?'—':'HR Operations',last:next==='مكتملة'?'تم الإغلاق':'تم تحديث الحالة'}:t));notify(`تم تحديث حالة المعاملة إلى ${next}`)};
 return <div className="app"><Sidebar page={page} go={go} open={mobile}/><main className="main"><Topbar company={company} role={role} roleId={roleId} setRole={setRoleId} companyId={companyId} setCompany={changeCompany} onMenu={()=>setMobile(!mobile)} onNotify={()=>setModal({type:'notifications'})}/><div className="demo-banner"><span><ShieldCheck size={13}/> هذه بيئة Demo ببيانات وهمية بالكامل — ليست نظامًا إنتاجيًا أو سجلًا قانونيًا.</span><span className="mono">{company.short} · {role.label}</span></div><Routes page={page} company={company} role={role} employees={employees} transactions={transactions} leaves={leaveData} go={go} openModal={setModal} addEmployee={addEmployee} createLeave={createLeave} act={act}/></main>{toast&&<div className="toast">{toast}</div>}{modal&&<Modal modal={modal} close={()=>setModal(null)} employees={employees} transactions={transactions} company={company} addEmployee={addEmployee} createLeave={createLeave}/>}</div>
}
function Sidebar({page,go,open}){return <aside className={'sidebar '+(open?'open':'')}><div className="brand"><div className="logo">H</div><div><strong>HR Core</strong><small>نظام تشغيل الموارد البشرية</small></div></div>{nav.map((s,i)=><div key={i}><div className="nav-section">{s.section}</div>{s.items.map(([id,label,Icon])=><button key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>go(id)}><Icon size={16}/><span>{label}</span></button>)}</div>)}</aside>}
function Topbar({company,role,roleId,setRole,companyId,setCompany,onMenu,onNotify}){return <header className="topbar"><button className="icon-btn mobile-menu" onClick={onMenu}><Menu size={18}/></button><button className="company-switch" onClick={()=>{const ids=companies.map(c=>c.id);setCompany(ids[(ids.indexOf(companyId)+1)%ids.length])}}><span className="company-mark">{company.short.slice(0,2)}</span><span className="company-name"><b>{company.name}</b><small>{company.industry}</small></span><ChevronDown size={15}/></button><div className="top-actions"><button className="icon-btn" onClick={onNotify}><Bell size={17}/></button><button className="btn"><RefreshCw size={14}/> Demo Mode</button><select className="select demo-user" value={roleId} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select><div className="avatar">م</div></div></header>}
function Routes(p){switch(p.page){case' employees':return null;case'employees':return <Employees {...p}/>;case'employee-new':return <EmployeeNew {...p}/>;case'org':return <Org {...p}/>;case'transactions':case'pending':case'completed':case'rejected':case'my-transactions':return <Transactions {...p} filter={p.page}/>;case'leaves':return <Leaves {...p}/>;case'balances':return <Balances {...p}/>;case'leave-calendar':return <LeaveCalendar {...p}/>;case'payroll':return <Payroll {...p}/>;case'payslip':return <Payslip {...p}/>;case'eos':return <EOS {...p}/>;case'documents':case'expiring':return <Documents {...p} expiring={p.page==='expiring'}/>;case'reports':return <Reports {...p}/>;case'settings':return <SettingsPage {...p}/>;default:return <Dashboard {...p}/>}}
function Page({title,desc,children,actions}){return <div className="content"><div className="page-head"><div><div className="eyebrow">HR Core / {title}</div><h1 className="page-title">{title}</h1><p className="page-desc">{desc}</p></div><div className="actions">{actions}</div></div>{children}</div>}
function Dashboard({company,employees,transactions,go,openModal}){const total=company.employees;const payroll=employees.reduce((s,e)=>s+e.salary,0);return <Page title="نظرة تنفيذية" desc={`لوحة تشغيل موحدة لـ ${company.name}`} actions={<><button className="btn primary" onClick={()=>openModal({type:'leave'})}><Plus size={15}/> طلب إجازة</button><button className="btn" onClick={()=>go('employee-new')}><Users size={15}/> إضافة موظف</button></>}><div className="grid kpis">{[['إجمالي الموظفين',total,'+4.2%'],['السعوديون',Math.round(total*.71),'71%'],['غير السعوديين',Math.round(total*.29),'29%'],['موظفون جدد',38,'هذا الشهر'],['تحت التجربة',26,'حالياً'],['معاملات معلقة',14,'تحتاج إجراء']].map(x=><div className="kpi" key={x[0]}><div className="kpi-top"><span>{x[0]}</span><span>↗</span></div><div className="kpi-value">{x[1].toLocaleString('ar-SA')}</div><div className="kpi-trend">{x[2]}</div></div>)}</div><div className="grid dashboard-grid" style={{marginTop:16}}><div className="panel"><div className="panel-head"><span className="panel-title">توزيع الموظفين حسب الإدارة</span><button className="link" onClick={()=>go('employees')}>عرض التفاصيل</button></div><div className="panel-body">{depts.slice(0,7).map((d,i)=><div className="bar-row" key={d}><div className="bar-label"><span>{d}</span><b>{(90-i*8).toLocaleString('ar-SA')}</b></div><div className="bar-track"><div className="bar-fill" style={{width:`${90-i*8}%`}}/></div></div>)}</div></div><div className="panel"><div className="panel-head"><span className="panel-title">السعودة</span><span className="badge success">مستقر</span></div><div className="panel-body"><div className="donut"/><div className="stat-list" style={{marginTop:15}}><div className="stat-item"><span>سعوديون</span><b>71%</b></div><div className="stat-item"><span>غير سعوديين</span><b>29%</b></div></div></div></div></div><div className="grid quick-grid" style={{marginTop:16}}>{[['إضافة موظف',Users,'employee-new'],['إنشاء معاملة',FileText,'transactions'],['طلب إجازة',CalendarDays,'leaves'],['تعريف بالراتب',WalletCards,'payslip']].map(([t,I,p])=><button className="quick" key={t} onClick={()=>go(p)}><I size={18}/><b>{t}</b><small>ابدأ الإجراء من هنا</small></button>)}</div><div className="grid dashboard-grid" style={{marginTop:16}}><div className="panel"><div className="panel-head"><span className="panel-title">آخر المعاملات</span><button className="link" onClick={()=>go('transactions')}>كل المعاملات</button></div><TransactionTable transactions={transactions.slice(0,5)} compact/></div><div className="panel"><div className="panel-head"><span className="panel-title">مركز التنبيهات</span><Bell size={16}/></div><div className="panel-body">{notifications.map((n,i)=><div className={'notice '+n[0]} key={i}><AlertTriangle size={16}/><div><strong>{n[0]==='warning'?'تنبيه تشغيلي':n[0]==='info'?'اعتماد مطلوب':'تمت المعالجة'}</strong>{n[1]}<div className="eyebrow" style={{marginTop:3}}>{n[2]}</div></div></div>)}</div></div></div></Page>}
function TransactionTable({transactions,compact}){return <div className="table-wrap"><table className="table"><thead><tr><th>رقم المعاملة</th><th>النوع</th><th>الموظف</th><th>التاريخ</th><th>الحالة</th><th>الأولوية</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td className="mono">{t.id}</td><td>{t.type}</td><td>{t.employee}</td><td>{t.date}</td><td><span className={'badge '+statusClass(t.status)}>{t.status}</span></td><td>{t.priority}</td></tr>)}</tbody></table>{!transactions.length&&<div className="empty">لا توجد معاملات في هذه القائمة</div>}</div>}
function Employees({employees,go}){const [q,setQ]=useState('');const [dept,setDept]=useState('');const list=employees.filter(e=>(e.name.includes(q)||e.id.toLowerCase().includes(q.toLowerCase()))&&(!dept||e.dept===dept));return <Page title="جميع الموظفين" desc="دليل القوى العاملة وبيانات الموظفين التشغيلية" actions={<><button className="btn primary" onClick={()=>go('employee-new')}><Plus size={15}/> إضافة موظف</button><button className="btn"><Download size={14}/> تصدير</button></>}><div className="panel"><div className="toolbar"><Search size={17} style={{marginTop:10,color:'#8a97a7'}}/><input className="search" placeholder="ابحث بالاسم أو الرقم الوظيفي" value={q} onChange={e=>setQ(e.target.value)}/><select className="select" value={dept} onChange={e=>setDept(e.target.value)}><option value="">كل الإدارات</option>{depts.map(d=><option key={d}>{d}</option>)}</select><button className="btn"><Filter size={14}/> عوامل إضافية</button></div><table className="table"><thead><tr><th>الموظف</th><th>الرقم</th><th>المسمى</th><th>الإدارة</th><th>الفرع</th><th>الجنسية</th><th>الحالة</th></tr></thead><tbody>{list.slice(0,50).map(e=><tr key={e.id}><td><button className="link" onClick={()=>go('employee:'+e.id)}>{e.name}</button></td><td className="mono">{e.id}</td><td>{e.job}</td><td>{e.dept}</td><td>{e.branch}</td><td>{e.nationality}</td><td><span className={'badge '+(e.status==='على رأس العمل'?'success':'info')}>{e.status}</span></td></tr>)}</tbody></table><div className="panel-body" style={{display:'flex',justifyContent:'space-between',fontSize:11,color:'#718096'}}><span>عرض {Math.min(50,list.length)} من {list.length.toLocaleString('ar-SA')} نتيجة</span><span>1 / {Math.max(1,Math.ceil(list.length/50))}</span></div></div></Page>}
function EmployeeNew({addEmployee}){return <Page title="إضافة موظف" desc="إنشاء سجل موظف Demo جديد وربطه بالقوى العاملة"><div className="panel"><div className="panel-body"><EmployeeForm onSubmit={addEmployee}/></div></div></Page>}
function EmployeeForm({onSubmit}){const [f,setF]=useState({name:'',job:jobs[0],dept:depts[0],branch:branches[0],nationality:'سعودي',salary:9000,joinDate:'17/09/2026'});return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}}><div className="form-grid">{[['name','الاسم الكامل','text'],['job','المسمى الوظيفي','select'],['dept','الإدارة','select'],['branch','الفرع','select'],['nationality','الجنسية','select'],['salary','الراتب الأساسي','number'],['joinDate','تاريخ المباشرة','text']].map(([k,l,t])=><div className="field" key={k}><label>{l}</label>{t==='select'?<select value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}>{(k==='job'?jobs:k==='dept'?depts:k==='branch'?branches:['سعودي','غير سعودي']).map(v=><option key={v}>{v}</option>)}</select>:<input required={k==='name'} type={t} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>}</div>)}</div><div style={{marginTop:18}}><button className="btn primary" type="submit"><CheckCircle2 size={15}/> حفظ الموظف</button></div></form>}
function Transactions({transactions,filter,act}){const [q,setQ]=useState('');let list=transactions.filter(t=>t.employee.includes(q)||t.id.includes(q));if(filter==='pending')list=list.filter(t=>['بانتظار الاعتماد','مراجعة HR','تنفيذ'].includes(t.status));if(filter==='completed')list=list.filter(t=>t.status==='مكتملة');if(filter==='rejected')list=list.filter(t=>t.status==='مرفوضة');return <Page title="مركز المعاملات" desc="تتبع دورة المعاملات من الإنشاء حتى الإغلاق" actions={<button className="btn primary"><Plus size={15}/> إنشاء معاملة</button>}><div className="panel"><div className="toolbar"><Search size={17} style={{marginTop:10,color:'#8a97a7'}}/><input className="search" placeholder="ابحث في رقم المعاملة أو الموظف" value={q} onChange={e=>setQ(e.target.value)}/><select className="select"><option>كل الحالات</option><option>بانتظار الاعتماد</option><option>مكتملة</option></select><button className="btn"><Download size={14}/> تصدير</button></div><table className="table"><thead><tr><th>رقم</th><th>النوع</th><th>الموظف</th><th>مقدم الطلب</th><th>التاريخ</th><th>الحالة</th><th>المسؤول الحالي</th><th>إجراء</th></tr></thead><tbody>{list.map(t=><tr key={t.id}><td className="mono">{t.id}</td><td>{t.type}</td><td>{t.employee}</td><td>{t.requester}</td><td>{t.date}</td><td><span className={'badge '+statusClass(t.status)}>{t.status}</span></td><td>{t.current}</td><td><button className="btn" onClick={()=>act(t.id,t.status==='مكتملة'?'مراجعة HR':'مكتملة')}><Eye size={13}/> {t.status==='مكتملة'?'عرض':'معالجة'}</button></td></tr>)}</tbody></table></div></Page>}
function Leaves({leaves,openModal}){return <Page title="إدارة الإجازات" desc="الأرصدة والطلبات والموافقات في مسار واحد" actions={<button className="btn primary" onClick={()=>openModal({type:'leave'})}><Plus size={15}/> طلب إجازة</button>}><div className="grid kpis" style={{gridTemplateColumns:'repeat(4,1fr)'}}>{[['الرصيد المتاح',18,'يوم'],['المستخدم هذا العام',12,'يوم'],['طلبات معلقة',4,'طلب'],['إجازات حالية',9,'موظف']].map(x=><div className="kpi" key={x[0]}><div className="kpi-top"><span>{x[0]}</span></div><div className="kpi-value">{x[1]}</div><div className="kpi-trend">{x[2]}</div></div>)}</div><div className="panel" style={{marginTop:16}}><div className="panel-head"><span className="panel-title">طلبات الإجازات</span></div><table className="table"><thead><tr><th>الموظف</th><th>النوع</th><th>من</th><th>إلى</th><th>الأيام</th><th>الحالة</th><th>الرصيد بعد الطلب</th></tr></thead><tbody>{leaves.map(l=><tr key={l.id}><td>{l.employee}</td><td>{l.type}</td><td>{l.from}</td><td>{l.to}</td><td>{l.days}</td><td><span className={'badge '+statusClass(l.status)}>{l.status}</span></td><td>{l.balance===null?'—':l.balance-l.days}</td></tr>)}</tbody></table></div></Page>}
function Balances({employees}){return <Page title="أرصدة الإجازات" desc="ملخص أرصدة الإجازات حسب الموظف"><div className="panel"><table className="table"><thead><tr><th>الموظف</th><th>السنوية</th><th>المستخدم</th><th>المتبقي</th><th>حالة الرصيد</th></tr></thead><tbody>{employees.slice(0,25).map((e,i)=><tr key={e.id}><td>{e.name}</td><td>30</td><td>{(i%13)+2}</td><td>{28-(i%13)}</td><td><span className="badge success">طبيعي</span></td></tr>)}</tbody></table></div></Page>}
function LeaveCalendar({leaves}){return <Page title="تقويم الإجازات" desc="رؤية تشغيلية للإجازات الحالية والمجدولة"><div className="panel"><div className="panel-body"><div className="grid" style={{gridTemplateColumns:'repeat(7,1fr)',gap:6}}>{['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map(d=><b key={d} style={{fontSize:11,textAlign:'center',padding:8,color:'#718096'}}>{d}</b>)}{Array.from({length:35},(_,i)=><div key={i} style={{minHeight:80,border:'1px solid #edf0f3',borderRadius:7,padding:7,fontSize:10}}><b>{(i%30)+1}</b>{i===21&&<div className="badge info" style={{marginTop:7}}>محمد · 4 أيام</div>}</div>)}</div></div></div></Page>}
function Payroll({employees}){const total=employees.reduce((s,e)=>s+e.salary,0);return <Page title="مسير الرواتب" desc="مسير Demo لشهر سبتمبر 2026" actions={<button className="btn primary"><CheckCircle2 size={15}/> اعتماد المسير</button>}><div className="grid kpis" style={{gridTemplateColumns:'repeat(4,1fr)'}}>{[['عدد الموظفين',employees.length],['إجمالي الأساسي',money(total)],['إجمالي الخصومات',money(total*.045)],['صافي الرواتب',money(total*.955)]].map(x=><div className="kpi" key={x[0]}><div className="kpi-top"><span>{x[0]}</span></div><div className="kpi-value" style={{fontSize:20}}>{x[1]}</div></div>)}</div><div className="panel" style={{marginTop:16}}><div className="panel-head"><span className="panel-title">سبتمبر 2026</span><span className="badge success">مسودة Demo</span></div><table className="table"><thead><tr><th>الموظف</th><th>الأساسي</th><th>السكن</th><th>النقل</th><th>بدلات أخرى</th><th>خصومات</th><th>الصافي</th></tr></thead><tbody>{employees.slice(0,25).map(e=><tr key={e.id}><td>{e.name}</td><td>{money(e.salary)}</td><td>{money(e.salary*.25)}</td><td>{money(700)}</td><td>{money(350)}</td><td>{money(e.salary*.045)}</td><td><b>{money(e.salary*1.2055)}</b></td></tr>)}</tbody></table></div></Page>}
function Payslip({employees}){const e=employees[0];return <Page title="مفردات الراتب" desc="كشف راتب قابل للطباعة — بيانات Demo"><div className="pay-slip"><div className="pay-head"><div><b>HR Core</b><div className="eyebrow">مفردات راتب — سبتمبر 2026</div></div><div style={{textAlign:'left'}}><b>{e.name}</b><div className="eyebrow">{e.id}</div></div></div><div className="pay-lines">{[['الراتب الأساسي',e.salary],['بدل السكن',e.salary*.25],['بدل النقل',700],['بدلات أخرى',350],['الخصومات',-e.salary*.045]].map(x=><div className="pay-line" key={x[0]}><span>{x[0]}</span><b>{money(x[1])}</b></div>)}</div><div className="net"><span>صافي الراتب</span><span>{money(e.salary*1.2055)}</span></div></div></Page>}
function EOS({employees}){const e=employees[0];const service=4.7;const wage=e.salary;const calc=Math.round(wage*service/2);return <Page title="حاسبة نهاية الخدمة" desc="حساب تعليمي مبني على بيانات الموظف الوهمية"><div className="notice warning"><AlertTriangle size={17}/><div><strong>تنبيه Demo</strong> هذه الحسبة محاكاة تعليمية وليست حسبة قانونية معتمدة. يجب التحقق من الأنظمة والوقائع الفعلية قبل أي استخدام.</div></div><div className="panel" style={{marginTop:16}}><div className="panel-body"><div className="form-grid"><div className="field"><label>الموظف</label><select><option>{e.name} · {e.id}</option></select></div><div className="field"><label>سبب انتهاء العلاقة</label><select><option>استقالة</option><option>انتهاء عقد</option><option>إنهاء من صاحب العمل</option></select></div><div className="field"><label>تاريخ المباشرة</label><input value={e.joinDate} readOnly/></div><div className="field"><label>آخر يوم عمل</label><input value="17/09/2026" readOnly/></div><div className="field"><label>مدة الخدمة</label><input value={`${service} سنوات تقريبًا`} readOnly/></div><div className="field"><label>آخر أجر</label><input value={money(wage)} readOnly/></div></div><div className="kpi" style={{marginTop:18,background:'#f5faf9'}}><div className="kpi-top"><span>الاستحقاق المحاكى</span></div><div className="kpi-value">{money(calc)}</div><div className="eyebrow">تفصيل Demo: الأجر × مدة الخدمة × معامل محاكاة</div></div></div></div></Page>}
function Documents({employees,expiring}){const docs=employees.slice(0,18).map((e,i)=>({e,type:i%3===0?'هوية':i%3===1?'عقد':'شهادة',expiry:`${String((i%9)+1).padStart(2,'0')}/10/2026`,status:i%4===0?'ينتهي قريبًا':'ساري'}));const list=expiring?docs.filter(d=>d.status==='ينتهي قريبًا'):docs;return <Page title={expiring?'المستندات التي ستنتهي':'مركز المستندات'} desc="متابعة المستندات وحالات الانتهاء" actions={<button className="btn"><Download size={14}/> تصدير القائمة</button>}><div className="panel"><table className="table"><thead><tr><th>الموظف</th><th>المستند</th><th>تاريخ الإصدار</th><th>تاريخ الانتهاء</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{list.map((d,i)=><tr key={i}><td>{d.e.name}</td><td>{d.type}</td><td>01/01/2025</td><td>{d.expiry}</td><td><span className={'badge '+(d.status==='ساري'?'success':'warning')}>{d.status}</span></td><td><button className="btn"><Eye size={13}/> عرض</button></td></tr>)}</tbody></table></div></Page>}
function Org({employees}){return <Page title="الهيكل التنظيمي" desc="هيكل Demo قابل للاستعراض وربط الإدارات بالموظفين"><div className="org"><div className="org-node org-root"><b>الرئيس التنفيذي</b><div style={{fontSize:11,opacity:.75}}>CEO · الإدارة التنفيذية</div></div><div className="org-children">{['الموارد البشرية','المالية','تقنية المعلومات','المبيعات','العمليات','التسويق','المشتريات','الجودة'].map((d,i)=><div className="org-node" key={d}><b>{d}</b><div className="eyebrow">{35-i} موظف Demo</div><button className="link">عرض الموظفين ←</button></div>)}</div></div></Page>}
function Reports({company}){const reports=[['تقرير القوى العاملة','توزيع الموظفين حسب الإدارة والفرع'],['تقرير السعودة','نسبة السعوديين ومؤشرات التوطين'],['تقرير الدوران','حركة الانضمام والمغادرة'],['تقرير الغياب','الغياب والتأخيرات والانقطاعات'],['تقرير الإجازات','الاستهلاك والأرصدة والطلبات'],['تقرير الرواتب','تكلفة الرواتب والبدلات والخصومات'],['تقرير المعاملات','حجم المعاملات وأزمنة المعالجة']];return <Page title="التقارير" desc={`تقارير Demo تفاعلية لـ ${company.name}`}><div className="grid report-cards">{reports.map(([t,d])=><div className="panel" key={t}><div className="panel-body"><BarChart3 size={19}/><h3 style={{fontSize:14,margin:'10px 0 5px'}}>{t}</h3><p className="page-desc">{d}</p><div style={{marginTop:15,display:'flex',gap:7}}><button className="btn primary">فتح التقرير</button><button className="btn"><Download size={13}/> تصدير</button></div></div></div>)}</div></Page>}
function SettingsPage(){return <Page title="الإعدادات" desc="تهيئة بيئة Demo وصلاحيات المستخدمين وسير الموافقات"><div className="grid dashboard-grid"><div className="panel"><div className="panel-head"><span className="panel-title">بيانات الشركة</span></div><div className="panel-body"><div className="form-grid"><div className="field"><label>اسم الشركة</label><input value="شركة النخبة للتجارة" readOnly/></div><div className="field"><label>اللغة</label><select><option>العربية (RTL)</option><option>English</option></select></div><div className="field"><label>العملة</label><select><option>ريال سعودي (SAR)</option></select></div><div className="field"><label>المنطقة الزمنية</label><select><option>Asia/Riyadh</option></select></div></div></div></div><div className="panel"><div className="panel-head"><span className="panel-title">الأدوار</span></div><div className="panel-body">{roles.map(r=><div className="stat-item" key={r.id}><span>{r.label}</span><span className="badge success">مفعل</span></div>)}</div></div></div></Page>}
function Modal({modal,close,employees,addEmployee,createLeave,transactions}){if(modal.type==='notifications')return <div className="modal-back" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h3>مركز التنبيهات</h3><button className="close" onClick={close}><X/></button></div><div className="modal-body">{notifications.map((n,i)=><div className={'notice '+n[0]} key={i}><AlertTriangle size={16}/><div>{n[1]}<div className="eyebrow">الوحدة: {n[2]}</div></div></div>)}</div></div></div>;
 if(modal.type==='employee')return null;
 if(modal.type==='leave')return <LeaveModal close={close} employees={employees} createLeave={createLeave}/>;
 return <div className="modal-back"><div className="modal"><div className="modal-head"><h3>إجراء Demo</h3><button className="close" onClick={close}><X/></button></div><div className="modal-body">تم فتح نافذة تفاعلية. يمكنك متابعة العملية من مركز المعاملات.</div><div className="modal-foot"><button className="btn primary" onClick={close}>متابعة</button></div></div></div>}
function LeaveModal({close,employees,createLeave}){const [f,setF]=useState({employee:employees[0]?.name||'',type:'سنوية',from:'21/09/2026',to:'24/09/2026',reason:''});const days=daysBetween(f.from.split('/').reverse().join('-'),f.to.split('/').reverse().join('-'));return <div className="modal-back" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h3>طلب إجازة</h3><button className="close" onClick={close}><X/></button></div><div className="modal-body"><div className="form-grid"><div className="field"><label>الموظف</label><select value={f.employee} onChange={e=>setF({...f,employee:e.target.value})}>{employees.slice(0,50).map(e=><option key={e.id}>{e.name}</option>)}</select></div><div className="field"><label>نوع الإجازة</label><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>سنوية</option><option>غير مدفوعة</option><option>مرضية</option></select></div><div className="field"><label>تاريخ البداية</label><input type="date" value={f.from.split('/').reverse().join('-')} onChange={e=>setF({...f,from:e.target.value.split('-').reverse().join('/')})}/></div><div className="field"><label>تاريخ النهاية</label><input type="date" value={f.to.split('/').reverse().join('-')} onChange={e=>setF({...f,to:e.target.value.split('-').reverse().join('/')})}/></div><div className="field full"><label>السبب</label><textarea rows="3" value={f.reason} onChange={e=>setF({...f,reason:e.target.value})}/></div></div><div className="notice info" style={{marginTop:14}}><CalendarDays size={16}/><div><strong>ملخص الطلب</strong>عدد الأيام: {days} · الرصيد قبل الطلب: 18 يوم · الرصيد بعد الطلب: {Math.max(0,18-days)} يوم<br/><span style={{fontSize:10}}>سيتم التحقق من التداخل عند الربط بقاعدة بيانات حقيقية.</span></div></div></div><div className="modal-foot"><button className="btn" onClick={close}>إلغاء</button><button className="btn primary" onClick={()=>createLeave({...f,days})}><Send size={14}/> إرسال الطلب</button></div></div></div>}
function EmployeeProfile({employee,go}){const [tab,setTab]=useState('البيانات الشخصية');return <Page title="ملف الموظف" desc="عرض تشغيلي متكامل لسجل الموظف" actions={<button className="btn" onClick={()=>go('employees')}><ArrowLeft size={14}/> العودة للموظفين</button>}><div className="profile"><div className="profile-card"><div className="profile-avatar">{employee.name.slice(0,1)}</div><div className="profile-name">{employee.name}</div><div className="profile-id mono">{employee.id}</div><div style={{marginTop:10}}><span className="badge success">على رأس العمل</span></div><div className="meta"><div><span>المسمى</span><b>{employee.job}</b></div><div><span>الإدارة</span><b>{employee.dept}</b></div><div><span>الفرع</span><b>{employee.branch}</b></div><div><span>الراتب</span><b>{money(employee.salary)}</b></div></div></div><div className="panel"><div className="tabs">{['البيانات الشخصية','الوظيفة','العقد','الراتب','الحضور','الإجازات','المستندات','المعاملات','السجل الوظيفي'].map(t=><button className={'tab '+(tab===t?'active':'')} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="panel-body">{tab==='السجل الوظيفي'?<Timeline/>:<div className="form-grid">{[['الاسم',employee.name],['الرقم الوظيفي',employee.id],['الجنسية',employee.nationality],['البريد',employee.email],['المسمى',employee.job],['الإدارة',employee.dept],['الفرع',employee.branch],['تاريخ المباشرة',employee.joinDate]].map(x=><div className="field" key={x[0]}><label>{x[0]}</label><input value={x[1]} readOnly/></div>)}</div>}</div></div></div></Page>}
function Timeline(){return <div className="timeline">{[['01/01/2022','مباشرة الموظف','تم إنشاء سجل الموظف وبدء العلاقة الوظيفية'],['01/01/2024','ترقية','تغيير المسمى الوظيفي ضمن المسار الوظيفي'],['01/06/2025','نقل إلى الموارد البشرية','تحديث الإدارة والهيكل التنظيمي'],['01/01/2026','تعديل راتب','تم تحديث عناصر الأجر في السجل']].map(e=><div className="event" key={e[0]}><span className="dot"/><time>{e[0]}</time><strong>{e[1]}</strong><span>{e[2]}</span></div>)}</div>}
const oldRoutes=Routes;Routes=function(p){if(p.page.startsWith('employee:')){const e=p.employees.find(x=>x.id===p.page.split(':')[1])||p.employees[0];return <EmployeeProfile employee={e} go={p.go}/>};return oldRoutes(p)};
createRoot(document.getElementById('root')).render(<App/>);
