import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,ArrowLeftRight,WalletCards,BarChart3,Settings,ShieldCheck,FileClock,Bell,LogOut,Menu,Plus,Check,RotateCcw,XCircle,Lock,RefreshCw,Building2,Workflow,ChevronDown} from 'lucide-react';
import './styles/main.css';
const api=async(path,opt={})=>{const r=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||'حدث خطأ');return d};
const nav=[['dashboard','لوحة التحكم',LayoutDashboard,'dashboard.view'],['employees','الموظفون',Users,'employees.view'],['transactions','المعاملات',ArrowLeftRight,'transactions.view'],['payroll','الرواتب',WalletCards,'payroll.view'],['reports','التقارير',BarChart3,'reports.view'],['organization','التنظيم',Building2,'employees.view'],['admin','إدارة النظام',ShieldCheck,'roles.view'],['audit','سجل العمليات',FileClock,'audit.view']];
function Login({onLogin}){const [username,setU]=useState('admin'),[password,setP]=useState('1234'),[loading,setL]=useState(false),[err,setE]=useState('');return <div className="login"><div className="login-card"><div className="brand-mark">HR</div><h1>HR Core</h1><p>منصة الموارد البشرية المؤسسية</p>{err&&<div className="alert error">{err}</div>}<label>اسم المستخدم<input value={username} onChange={e=>setU(e.target.value)} /></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setP(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} /></label><button className="primary full" disabled={loading} onClick={submit}>{loading?'جارٍ الدخول…':'تسجيل الدخول'}</button><small>بيانات الاختبار الأولية: admin / 1234</small></div></div>;function submit(){setL(true);setE('');api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})}).then(onLogin).catch(e=>setE(e.message)).finally(()=>setL(false))}}
function App(){const [user,setUser]=useState(null),[data,setData]=useState(null),[page,setPage]=useState('dashboard'),[mobile,setMobile]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{api('/api/auth/me').then(x=>setUser(x.user)).catch(()=>{})},[]);useEffect(()=>{if(user)refresh()},[user]);async function refresh(){setBusy(true);try{setData(await api('/api/state'))}catch(e){console.error(e)}finally{setBusy(false)}}if(!user)return <Login onLogin={u=>setUser(u)}/>;const perms=new Set(data?.permissions?.filter(p=>p.id)?.map(p=>p.id)||[]);const visible=nav.filter(n=>user.roleName==='مدير النظام'||perms.has(n[3]));return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="side-brand"><div className="brand-mark small">HR</div><div><b>HR Core</b><span>Enterprise</span></div></div><nav>{visible.map(([id,label,I])=><button key={id} className={page===id?'nav active':'nav'} onClick={()=>{setPage(id);setMobile(false)}}><I size={19}/><span>{label}</span></button>)}</nav><div className="side-bottom"><button className="nav" onClick={()=>setPage('settings')}><Settings size={19}/><span>الإعدادات</span></button><button className="nav danger" onClick={async()=>{await api('/api/auth/logout',{method:'DELETE'});location.reload()}}><LogOut size={19}/><span>تسجيل الخروج</span></button></div></aside><main><header><button className="icon mobile-menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><div className="crumb">HR Core / {label(page)}</div><h2>{label(page)}</h2></div><div className="header-actions"><button className="icon" onClick={refresh}><RefreshCw size={18}/></button><button className="icon notification"><Bell size={18}/><i>{data?.notifications?.filter(n=>!n.read_at).length||0}</i></button><div className="user-chip"><span>{user.name}</span><small>{user.roleName}</small></div></div></header><section className="content">{busy&&<div className="loading-bar"/>}<Page page={page} data={data||{}} user={user} refresh={refresh}/></section></main></div>}
function label(p){return nav.find(n=>n[0]===p)?.[1]||({'settings':'الإعدادات'}[p]||p)}
function Page({page,data,user,refresh}){if(page==='dashboard')return <Dashboard data={data} user={user}/>;if(page==='employees')return <Employees data={data} refresh={refresh}/>;if(page==='transactions')return <Transactions data={data} refresh={refresh}/>;if(page==='payroll')return <Payroll data={data} refresh={refresh}/>;if(page==='reports')return <Reports/>;if(page==='organization')return <Organization data={data}/>;if(page==='admin')return <Admin data={data} refresh={refresh}/>;if(page==='audit')return <Audit/>;return <SettingsPage/>}
function Dashboard({data,user}){const emp=data.employees?.length||0,tx=data.transactions?.length||0,open=data.transactions?.filter(x=>x.status==='قيد الإجراء').length||0;return <><div className="hero"><div><span className="eyebrow">نظرة تشغيلية</span><h1>مرحبًا، {user.name}</h1><p>هذه هي مساحة العمل الموحدة للموظفين والمعاملات والرواتب.</p></div><div className="hero-meta"><span>الحالة</span><b>النظام متصل</b></div></div><div className="cards"><Card title="الموظفون" value={emp} icon={Users}/><Card title="المعاملات" value={tx} icon={ArrowLeftRight}/><Card title="بانتظار الإجراء" value={open} icon={Workflow}/><Card title="إشعارات غير مقروءة" value={data.notifications?.filter(n=>!n.read_at).length||0} icon={Bell}/></div><div className="grid2"><Panel title="آخر المعاملات"><Table headers={['المعاملة','الموظف','الحالة','التاريخ']} rows={(data.transactions||[]).slice(0,7).map(t=>[t.definition_name,t.employee_name||'—',<Status s={t.status}/>,fmt(t.created_at)])}/></Panel><Panel title="ملخص النظام"><div className="summary-list"><div><span>الدور</span><b>{user.roleName}</b></div><div><span>الصلاحيات المحملة</span><b>{data.permissions?.length||0}</b></div><div><span>أنواع المعاملات</span><b>{data.transactionDefinitions?.length||0}</b></div><div><span>تشغيل Payroll</span><b>{data.payrollRuns?.length||0}</b></div></div></Panel></div></>}
const Card=({title,value,icon:I})=><div className="card"><div className="card-icon"><I size={20}/></div><span>{title}</span><strong>{value}</strong></div>;
const Panel=({title,children,action})=><div className="panel"><div className="panel-head"><h3>{title}</h3>{action}</div>{children}</div>;
const Table=({headers,rows})=><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty">لا توجد بيانات</td></tr>}</tbody></table></div>;
const Status=({s})=><span className={'status '+({'مكتملة':'success','مرفوضة':'danger','معادة للتعديل':'warning','قيد الإجراء':'info','مغلقة':'neutral'}[s]||'neutral')}>{s}</span>;
function Employees({data,refresh}){const [q,setQ]=useState('');const rows=(data.employees||[]).filter(e=>(e.name+' '+(e.job||'')+' '+(e.dept||'')).includes(q)).map(e=>[e.name,e.job,e.dept,e.status,Number(e.salary||0).toLocaleString('ar-SA')+' ر.س']);return <Panel title="دليل الموظفين" action={<input className="search" placeholder="بحث…" value={q} onChange={e=>setQ(e.target.value)}/> }><Table headers={['الموظف','المسمى','الإدارة','الحالة','الراتب الأساسي']} rows={rows}/></Panel>}
function Transactions({data,refresh}){const [def,setDef]=useState('');const [vals,setVals]=useState('{}');const [msg,setMsg]=useState('');async function create(){try{await api('/api/transactions',{method:'POST',body:JSON.stringify({definition_id:def,values:JSON.parse(vals)})});setMsg('تم إنشاء المعاملة بنجاح');refresh()}catch(e){setMsg(e.message)}}return <div className="grid2"><Panel title="قائمة المعاملات"><Table headers={['النوع','الموظف','الحالة','المقدم','التاريخ']} rows={(data.transactions||[]).map(t=>[t.definition_name,t.employee_name||'—',<Status s={t.status}/>,t.requester_name||'—',fmt(t.created_at)])}/></Panel><Panel title="إنشاء معاملة"><label>نوع المعاملة<select value={def} onChange={e=>setDef(e.target.value)}><option value="">اختر…</option>{(data.transactionDefinitions||[]).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>بيانات الطلب <textarea rows="7" value={vals} onChange={e=>setVals(e.target.value)}/></label><button className="primary" disabled={!def} onClick={create}><Plus size={17}/> إنشاء</button>{msg&&<div className="alert">{msg}</div>}</Panel></div>}
function Payroll({data,refresh}){const [start,setS]=useState(new Date().toISOString().slice(0,7)+'-01'),[end,setE]=useState(new Date().toISOString().slice(0,7)+'-28'),[msg,setM]=useState('');async function calc(){try{const r=await api('/api/payroll',{method:'POST',body:JSON.stringify({start_date:start,end_date:end})});setM(`تم الاحتساب: ${r.summary.employees} موظف — صافي ${r.summary.net.toLocaleString('ar-SA')} ر.س`);refresh()}catch(e){setM(e.message)}}return <><div className="cards"><Card title="إجمالي Gross" value={(data.payrollRuns?.[0]?.gross_total||0).toLocaleString('ar-SA')} icon={WalletCards}/><Card title="الاستقطاعات" value={(data.payrollRuns?.[0]?.deductions_total||0).toLocaleString('ar-SA')} icon={ArrowLeftRight}/><Card title="صافي الرواتب" value={(data.payrollRuns?.[0]?.net_total||0).toLocaleString('ar-SA')} icon={Check}/><Card title="التشغيلات" value={data.payrollRuns?.length||0} icon={RefreshCw}/></div><Panel title="Payroll Engine" action={<button className="primary" onClick={calc}><RefreshCw size={16}/> احتساب فترة</button>}><div className="form-grid"><label>من<input type="date" value={start} onChange={e=>setS(e.target.value)}/></label><label>إلى<input type="date" value={end} onChange={e=>setE(e.target.value)}/></label></div>{msg&&<div className="alert success">{msg}</div>}<Table headers={['الفترة','الحالة','Gross','GOSI','Net']} rows={(data.payrollRuns||[]).map(r=>[r.period_code,<Status s={r.status}/>,Number(r.gross_total||0).toLocaleString('ar-SA'),Number(r.gosi_total||0).toLocaleString('ar-SA'),Number(r.net_total||0).toLocaleString('ar-SA')])}/></Panel></>}
function Reports(){const [r,setR]=useState(null);useEffect(()=>{api('/api/reports').then(setR).catch(()=>{})},[]);return <Panel title="التقارير"><div className="cards mini"><Card title="الموظفون" value={r?.summary?.employees||0} icon={Users}/><Card title="Gross المعتمد" value={Number(r?.summary?.payroll?.gross||0).toLocaleString('ar-SA')} icon={WalletCards}/><Card title="Net المعتمد" value={Number(r?.summary?.payroll?.net||0).toLocaleString('ar-SA')} icon={BarChart3}/></div><pre className="json">{JSON.stringify(r?.summary?.transactions||[],null,2)}</pre></Panel>}
function Organization({data}){return <div className="grid2"><Panel title="الإدارات"><Table headers={['الإدارة','الكود','الحالة']} rows={(data.departments||[]).map(d=>[d.name_ar,d.code||'—',d.active?'نشطة':'غير نشطة'])}/></Panel><Panel title="الهيكل"><div className="org-tree"><div className="org-node root">الشركة</div>{(data.departments||[]).map(d=><div className="org-node" key={d.id}>{d.name_ar}</div>)}</div></Panel></div>}
function Admin({data,refresh}){const [name,setName]=useState(''),[desc,setDesc]=useState('');async function create(){if(!name)return;await api('/api/roles',{method:'POST',body:JSON.stringify({name,description:desc,permissions:[]})});setName('');setDesc('');refresh()}return <div className="grid2"><Panel title="الأدوار" action={<div className="inline"><input placeholder="اسم الدور" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="الوصف" value={desc} onChange={e=>setDesc(e.target.value)}/><button className="primary" onClick={create}><Plus size={16}/> إنشاء</button></div>}><Table headers={['الدور','المستخدمون','الحالة']} rows={(data.roles||[]).map(r=>[r.name,r.user_count,r.active?'نشط':'معطل'])}/></Panel><Panel title="Permission Catalog"><Table headers={['الوحدة','الصلاحية','الوصف']} rows={(data.permissions||[]).map(p=>[p.module||'—',p.id,p.label_ar||p.description])}/></Panel></div>}
function Audit(){const [logs,setLogs]=useState([]);useEffect(()=>{api('/api/audit').then(x=>setLogs(x.logs||[])).catch(()=>{})},[]);return <Panel title="سجل العمليات"><Table headers={['المستخدم','الإجراء','المورد','المعرف','الوقت']} rows={logs.map(l=>[l.actor_name,l.action,l.entity_type,l.entity_id,fmt(l.created_at)])}/></Panel>}
function SettingsPage(){return <Panel title="إعدادات النظام"><div className="settings-grid"><div><h4>الأمان</h4><p>Session Cookie آمن، جلسة 8 ساعات، والتحقق من الصلاحيات في Backend.</p></div><div><h4>قاعدة البيانات</h4><p>Cloudflare D1 — hr-core — binding: DB</p></div><div><h4>اللغة</h4><p>العربية RTL مع بنية قابلة للتوسع.</p></div></div></Panel>}
const fmt=v=>v?new Date(v).toLocaleString('ar-SA'): '—';
createRoot(document.getElementById('root')).render(<App/>);
